before:
  hooks:
    - go mod tidy
builds:
  - id: "giserver"
    main: ./cmd/main.go
    binary: giserver
    ldflags:
      - -s -w -X main.VERSION=v{{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    hooks:
      post:
        - upx "{{ .Path }}"

archives:
  - id: "giserver"
    builds:
      - "giserver"
    format: binary
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
