package constant

const ExtendXmlTmpl = `<?xml version="1.0" encoding="UTF-8"?><sml:Layer xmlns:sml="http://www.supermap.com/sml">
<sml:Caption>%s</sml:Caption>
<sml:Description/>
<sml:DataSourceAlias>%s</sml:DataSourceAlias>
<sml:ConfigueDataTime>%s</sml:ConfigueDataTime>
<sml:LayerName>%s</sml:LayerName>
<sml:LayerType>OSGBLayer</sml:LayerType>
<sml:CacheFileType>%s</sml:CacheFileType>
<sml:Password/>
<sml:Options>
<sml:Visible>TRUE</sml:Visible>
<sml:Selectable>TRUE</sml:Selectable>
<sml:LoadingMode>All_Loading</sml:LoadingMode>
<sml:VectorFiltratePixSize>0</sml:VectorFiltratePixSize>
<sml:VisibleAltitudeMin>0.000000</sml:VisibleAltitudeMin>
<sml:VisibleAltitudeMax>0.000000</sml:VisibleAltitudeMax>
<sml:VisibleDistanceMax>47836027.500000</sml:VisibleDistanceMax>
<sml:VisibleDistanceMin>0.000000</sml:VisibleDistanceMin>
<sml:IsExcavation>FALSE</sml:IsExcavation>
<sml:bUseGeoStyle>TRUE</sml:bUseGeoStyle>
<sml:AutoRelease>FALSE</sml:AutoRelease>
<sml:ShadowType>NONE</sml:ShadowType>
</sml:Options>
<sml:LayerStyle>
<sml:Style>
<sml:MarkerStyle>0</sml:MarkerStyle>
<sml:MarkerSize>1.5</sml:MarkerSize>
<sml:MarkerAngle>0</sml:MarkerAngle>
<sml:MarkerWidth>15</sml:MarkerWidth>
<sml:MarkerHeight>15</sml:MarkerHeight>
<sml:MarkerPicturePath/>
<sml:MarkerSVGPath/>
<sml:LineStyle>0</sml:LineStyle>
<sml:LineWidth>1</sml:LineWidth>
<sml:LineColor>RGB(0,0,130816)</sml:LineColor>
<sml:LineCapStyle>0</sml:LineCapStyle>
<sml:LineJoinStyle>0</sml:LineJoinStyle>
<sml:FillStyle>0</sml:FillStyle>
<sml:FillForeColor>RGB(189,235,131071)</sml:FillForeColor>
<sml:FillBackColor>RGB(255,255,131071)</sml:FillBackColor>
<sml:FillBackOpaque>TRUE</sml:FillBackOpaque>
<sml:FillOpaqueRate>100</sml:FillOpaqueRate>
<sml:FillGradientType>None</sml:FillGradientType>
<sml:FillAngle>0</sml:FillAngle>
<sml:FillCenterOffsetX>0</sml:FillCenterOffsetX>
<sml:FillCenterOffsetY>0</sml:FillCenterOffsetY>
<sml:AcrossLongtitude>FALSE</sml:AcrossLongtitude>
<sml:Style3D>
<sml:PointSize>4.0</sml:PointSize>
<sml:ColorPoint>RGBA(1.000000,1.000000,1.000000,1.000000)</sml:ColorPoint>
<sml:LineWidth>1</sml:LineWidth>
<sml:Fill3DMode>FILL_FACE</sml:Fill3DMode>
<sml:ColorFill>RGBA(1.000000,1.000000,1.000000,1.000000)</sml:ColorFill>
<sml:LineColor>RGBA(1.000000,1.000000,1.000000,1.000000)</sml:LineColor>
<sml:IconScale>1.0</sml:IconScale>
<sml:TilingU>1.000000</sml:TilingU>
<sml:TilingV>1.000000</sml:TilingV>
<sml:TextureRepeatMode>RepeatTimes</sml:TextureRepeatMode>
<sml:TopTilingU>1.000000</sml:TopTilingU>
<sml:TopTilingV>1.000000</sml:TopTilingV>
<sml:TopTextureRepeatMode>RepeatTimes</sml:TopTextureRepeatMode>
<sml:IconName/>
<sml:SideTextureName/>
<sml:TopTextureName/>
<sml:BottomAltitude>0</sml:BottomAltitude>
<sml:ExtendHeight>0</sml:ExtendHeight>
<sml:AltitudeMode>Absolute</sml:AltitudeMode>
<sml:IconAnchor>
<sml:x>0.0000000000</sml:x>
<sml:y>0.0000000000</sml:y>
</sml:IconAnchor>
<sml:FixedPixelSize>TRUE</sml:FixedPixelSize>
<sml:BillboardMode>SCREEN_ALIGNED</sml:BillboardMode>
<sml:AnchorOffsetMode>FixedScale</sml:AnchorOffsetMode>
<sml:IsMarker3D>FALSE</sml:IsMarker3D>
<sml:LineStyle3D>LINE_SIMPLE</sml:LineStyle3D>
<sml:PipeSides>20</sml:PipeSides>
<sml:IsFiletEnable>TRUE</sml:IsFiletEnable>
<sml:IsTessellate>FALSE</sml:IsTessellate>
<sml:ScaleX>1.000000</sml:ScaleX>
<sml:ScaleY>1.000000</sml:ScaleY>
<sml:ScaleZ>1.000000</sml:ScaleZ>
<sml:RotateX>0.000000</sml:RotateX>
<sml:RotateY>0.000000</sml:RotateY>
<sml:RotateZ>0.000000</sml:RotateZ>
</sml:Style3D>
</sml:Style>
</sml:LayerStyle>
<sml:SelectStyle>
<sml:Style>
<sml:MarkerStyle>0</sml:MarkerStyle>
<sml:MarkerSize>2.5</sml:MarkerSize>
<sml:MarkerAngle>0</sml:MarkerAngle>
<sml:MarkerWidth>25</sml:MarkerWidth>
<sml:MarkerHeight>25</sml:MarkerHeight>
<sml:MarkerPicturePath/>
<sml:MarkerSVGPath/>
<sml:LineStyle>0</sml:LineStyle>
<sml:LineWidth>1.5</sml:LineWidth>
<sml:LineColor>RGB(0,0,130816)</sml:LineColor>
<sml:LineCapStyle>0</sml:LineCapStyle>
<sml:LineJoinStyle>0</sml:LineJoinStyle>
<sml:FillStyle>0</sml:FillStyle>
<sml:FillForeColor>RGB(178,178,131071)</sml:FillForeColor>
<sml:FillBackColor>RGB(255,255,131071)</sml:FillBackColor>
<sml:FillBackOpaque>TRUE</sml:FillBackOpaque>
<sml:FillOpaqueRate>100</sml:FillOpaqueRate>
<sml:FillGradientType>None</sml:FillGradientType>
<sml:FillAngle>0</sml:FillAngle>
<sml:FillCenterOffsetX>0</sml:FillCenterOffsetX>
<sml:FillCenterOffsetY>0</sml:FillCenterOffsetY>
<sml:AcrossLongtitude>FALSE</sml:AcrossLongtitude>
<sml:Style3D>
<sml:PointSize>4.0</sml:PointSize>
<sml:ColorPoint>RGBA(0.000000,0.000000,1.000000,1.000000)</sml:ColorPoint>
<sml:LineWidth>1</sml:LineWidth>
<sml:Fill3DMode>FILL_FACEANDLINE</sml:Fill3DMode>
<sml:ColorFill>RGBA(0.700000,0.700000,1.000000,1.000000)</sml:ColorFill>
<sml:LineColor>RGBA(0.000000,0.000000,1.000000,1.000000)</sml:LineColor>
<sml:IconScale>1.0</sml:IconScale>
<sml:TilingU>1.000000</sml:TilingU>
<sml:TilingV>1.000000</sml:TilingV>
<sml:TextureRepeatMode>RepeatTimes</sml:TextureRepeatMode>
<sml:TopTilingU>1.000000</sml:TopTilingU>
<sml:TopTilingV>1.000000</sml:TopTilingV>
<sml:TopTextureRepeatMode>RepeatTimes</sml:TopTextureRepeatMode>
<sml:IconName/>
<sml:SideTextureName/>
<sml:TopTextureName/>
<sml:BottomAltitude>0</sml:BottomAltitude>
<sml:ExtendHeight>0</sml:ExtendHeight>
<sml:AltitudeMode>ClampToGround</sml:AltitudeMode>
<sml:IconAnchor>
<sml:x>0.0000000000</sml:x>
<sml:y>0.0000000000</sml:y>
</sml:IconAnchor>
<sml:FixedPixelSize>TRUE</sml:FixedPixelSize>
<sml:BillboardMode>SCREEN_ALIGNED</sml:BillboardMode>
<sml:AnchorOffsetMode>FixedScale</sml:AnchorOffsetMode>
<sml:IsMarker3D>FALSE</sml:IsMarker3D>
<sml:LineStyle3D>LINE_SIMPLE</sml:LineStyle3D>
<sml:PipeSides>20</sml:PipeSides>
<sml:IsFiletEnable>TRUE</sml:IsFiletEnable>
<sml:IsTessellate>FALSE</sml:IsTessellate>
<sml:ScaleX>1.000000</sml:ScaleX>
<sml:ScaleY>1.000000</sml:ScaleY>
<sml:ScaleZ>1.000000</sml:ScaleZ>
<sml:RotateX>0.000000</sml:RotateX>
<sml:RotateY>0.000000</sml:RotateY>
<sml:RotateZ>0.000000</sml:RotateZ>
</sml:Style3D>
</sml:Style>
</sml:SelectStyle>
<sml:Exaggeration>1.000000</sml:Exaggeration>
<sml:LODRangeScale>1.000000</sml:LODRangeScale>
<sml:SelectionFiltrateByTransparency>0.000000</sml:SelectionFiltrateByTransparency>
<sml:PolygonOffset>
<sml:Constant>0.000000</sml:Constant>
<sml:SlopeScale>0.000000</sml:SlopeScale>
</sml:PolygonOffset>
<sml:MultiViewportVisible>65535</sml:MultiViewportVisible>
<sml:AlphaReject>0.100000</sml:AlphaReject>
<sml:ColorParams>
<sml:Brightness>1.000000</sml:Brightness>
<sml:Constrast>1.000000</sml:Constrast>
<sml:Hue>0.000000</sml:Hue>
<sml:Saturation>1.000000</sml:Saturation>
<sml:Gamma>1.000000</sml:Gamma>
</sml:ColorParams>
<sml:RenderCullMode>%s</sml:RenderCullMode>
<sml:MixColorType>MODULATE</sml:MixColorType>
<sml:WireFrameType>Quad</sml:WireFrameType>
<sml:IconRelatedTextLayerID>0</sml:IconRelatedTextLayerID>
<sml:PartlyTransparent>FALSE</sml:PartlyTransparent>
<sml:IsRenderMultipleTexure>TRUE</sml:IsRenderMultipleTexure>
</sml:Layer>`
